package modelo.canal.enums;

public enum TipoCanal {
	
	// TELEVISAO
	CANAL_ABERTO_DE_TELEVISAO,
	ASSINATURA_INDIVIDUAL_DE_TELEVISAO,
	PACOTE_DE_ASSINATURA_TELEVISAO,
	
	// BROADCASTING
	ABERTO_NA_INTERNET_BROADCASTING,
	ASSINATURA_INDIVIDUAL_DE_BROADCASTING;
}
