package modelo.canal.enums;

public enum TipoCanal {
	CANAL_ABERTO_DE_TELEVISAO,
	BROADCASTING_ABERTO_NA_INTERNET,
	PACOTE_DE_ASSINATURA,
	ASSINATURA_INDIVIDUAL_DE_TELEVISAO,
	ASSINATURA_INDIVIDUAL_DE_BROADCASTING;
}
