package telas.ouvintes;

public class OuvinteBotaoVoltar {
//TODO: RECEBER O NOME DA TELA PARA A QUAL DESEJA-SE VOLTAR
	//PROCURAR ESSE NOME NAS CLASSES DENTRO DO PACOTE TELAS
	//REALIZAR O DEVIDO PROCEDIMENTO
}
